### ISSUE TITLE
Request for BearerToken returns a 400

### ISSUE THREAD

**Issue by dhavalgujar** [alexa-labs/alexa-smart-home-wifi-simple-setup-sample#1]
Hi @ramezab!
So I have been trying to run the WSS sample, but I am facing an issue with getting the bearer token.
Here's a minimum working example to obtain a bearer token that the SDAE request must have:
```
import http.client
import json

clientId='amzn1.application-oa2-client.xxxx..'
clientSecret='secrethashgoeshere'

lwa_uri = 'api.amazon.com'
connection = http.client.HTTPSConnection(lwa_uri)
lwa_headers = {
    'Content-Type': "application/json;charset=UTF-8",
    'Cache-Control': "no-cache"
}
lwa_payload = {
    "grant_type": "client_credentials",
    "client_id": clientId,
    "client_secret":clientSecret,
    "scope": "alexa::device_association_report:write"
}
connection.request('POST', '/auth/o2/token', json.dumps(lwa_payload), lwa_headers)
response = connection.getresponse()

lwa_result = json.loads(response.read())
print('[LOG] HTTP Status code: ' + str(response.getcode()))
print('[LOG] LWA returned: ' + json.dumps(lwa_result))
```

I have tried running this with the Id-Secret pair obtained from my Alexa Smart Home Skill config page, but I get a:
```
[LOG] HTTP Status code: 400
[LOG] LWA returned: {"error_description": "The request has an invalid parameter : scope", "error": "invalid_scope"}
```
I also tried creating a LwA Security Profile from [this](https://developer.amazon.com/loginwithamazon/console/site/lwa/create-security-profile.html) page and got another Id-Secret pair from there, that had the same format, but even that gives me the same result.

Any idea what might be going wrong?

**Comment by ramezab** [comment]
Hello,

Can you share the skill Id you are working with?

**Comment by dhavalgujar** [comment]
Sure!
Here's my Skill Id: amzn1.ask.skill.1568e3b1-12f2-4a22-a1d4-3f1458e44fbf

**Comment by ramezab** [comment]
Looks like your developer account hasn’t accessed any of Smart Home skill capabilities before.
Can you share both you Client Id, and the region that this skill will launch in

**Comment by dhavalgujar** [comment]
Yes, my Client Id is: amzn1.application-oa2-client.11df84c09a3147b2b9ede2c2d40095bf
The regions this skill will launch in are: eu-west-1, us-west-2 and us-east-1.
However, it may be deployed to other regions as well.

**Comment by ramezab** [comment]
You Should be able to retry WSS session again using the same skill.

**Comment by dhavalgujar** [comment]
Got it all to work!
Thanks a lot! 👍
