### ISSUE TITLE
the device keys can't pass verification during the PROVISIONING stage

### ISSUE THREAD

**Issue by sksgits** [alexa-labs/alexa-smart-home-wifi-simple-setup-sample#2]
after Request a New Device Identifier and Attestation Keys step, we replace the keys we get from Amazon, during the Execute Wi-Fi provisionee state START_PROVISIONING stage, device post the nonce:

POST /api/v1/startProvisioningSession HTTP/1.1
Content-Length: 43
Host: dp-sps-na.amazon.com
Content-type: application/json

{"nonce":"iUryyB6ecF5BPC6FTJfOUuhIxhhP32m"}

 then server response body is :

{"canProceed":false,"waitTime":"PT30S"}

which cause the WSS C SDK can't continue to next step anymore, Can anyone help to fix this problem?
![image](https://user-images.githubusercontent.com/87159954/125015213-a060ff80-e0a1-11eb-9aa0-ce38aebcd4d5.png)

**Comment by quynh-stel** [comment]
@sksgits 
Did you able to resolve the above issue?
I'm getting the same issue as this.

**Comment by sksgits** [comment]
> @sksgits Did you able to resolve the above issue? I'm getting the same issue as this.

We resolve this by upload the device info, if you already have the permission to upload control log, that works too.

**Comment by quynh-stel** [comment]
>We resolve this by upload the device info

Can you please provide more detail about the device info, is that Submit test devices?
And how can I generate the barcode for my ESP32, @sksgits ?

Please help this!

**Comment by sksgits** [comment]
> > We resolve this by upload the device info
> 
> Can you please provide more detail about the device info, is that Submit test devices? And how can I generate the barcode for my ESP32, @sksgits ?
> 
> Please help this!

barcode is not necessary, and it may took some time for me to get the more detail about upload the device info, may I ask if you only use FFS in WiFi device or integrate with Matter over WiFi device?

**Comment by quynh-stel** [comment]
>may I ask if you only use FFS in WiFi device or integrate with Matter over WiFi device?

I'm trying to WSS only, not Matter over a WiFi device.

And I got the same error log on your issue.

My target is to be able to download the WiFi credentials list and access available WiFi.
I'm using ESP-WROOM-32

Thank you for your response, @sksgits

**Comment by sksgits** [comment]
> > may I ask if you only use FFS in WiFi device or integrate with Matter over WiFi device?
> 
> I'm trying to WSS only, not Matter over a WiFi device.
> 
> And I got the same error log on your issue.
> 
> My target is to be able to download the WiFi credentials list and access available WiFi. I'm using ESP-WROOM-32
> 
> Thank you for your response, @sksgits

I see, maybe we met the same issue. I'll check the details as soon as I can.

**Comment by quynh-stel** [comment]
> > > may I ask if you only use FFS in WiFi device or integrate with Matter over WiFi device?
> > 
> > 
> > I'm trying to WSS only, not Matter over a WiFi device.
> > And I got the same error log on your issue.
> > My target is to be able to download the WiFi credentials list and access available WiFi. I'm using ESP-WROOM-32
> > Thank you for your response, @sksgits
> 
> I see, maybe we met the same issue. I'll check the details as soon as I can.

Great, thank you @sksgits

**Comment by sksgits** [comment]
> > > > may I ask if you only use FFS in WiFi device or integrate with Matter over WiFi device?
> > > 
> > > 
> > > I'm trying to WSS only, not Matter over a WiFi device.
> > > And I got the same error log on your issue.
> > > My target is to be able to download the WiFi credentials list and access available WiFi. I'm using ESP-WROOM-32
> > > Thank you for your response, @sksgits
> > 
> > 
> > I see, maybe we met the same issue. I'll check the details as soon as I can.
> 
> Great, thank you @sksgits

Did you upload the control log or submit the test devices？

**Comment by quynh-stel** [comment]
> 

I submitted the test devices, but not with the control log, @sksgits 
Can you please help me with some questions?

- Did you use `simple_setup` WiFi or an Echo device?
- Did you submit test devices?
- How can you have the control log?

Thank you so much, @sksgits

**Comment by sksgits** [comment]
> > 
> 
> I submitted the test devices, but not with the control log, @sksgits Can you please help me with some questions?
> 
> * Did you use `simple_setup` WiFi or an Echo device?
> * Did you submit test devices?
> * How can you have the control log?
> 
> Thank you so much, @sksgits

You can check if your test devices’ CSV include the PUK, if you did please wait until the confirm email received.

1> we test with simple_setup.
2> we use submit test devices only.
3> control log requires permission so we didn't test with it.

**Comment by quynh-stel** [comment]
@sksgits 
So sorry because I keep troubling you, @sksgits 
But how can you generate the barcode?

Example this is the format:


```
2D barcode,ABV:OB04;UPC:136141484313;EAN:12345678;PID:APID;UUID:aaa4e0ae-8aac-4780-b742-4c5ab1973a00;OBD:A0UXujSA1Q+j+y0ArbmJebz+yIzzszWQn8IplfByNRxxh9ryC5p1IeNgx0XH55+z/on1yAkeFqR8AKVoVnyO9s0o6MOmjbEJOZTzI0+cIy4VmOEWllPEKT0A+x1zxvCiSRNcSnDZE5izH9kjTRS63Kk=;
```

- The ABV will always is `OB04`, as I know because this is for the BLE device.
- UPC: I tried to fake 12 digits but it didn't work
- EAN: I fake this too
- PID:APID, is this always `APID`?
- OBD: I got by the DHA public key I generated

Thank you, @sksgits

**Comment by quynh-stel** [comment]
@sksgits Hello, can you please help me with above questions?

**Comment by sksgits** [comment]
> 



> @sksgits So sorry because I keep troubling you, @sksgits But how can you generate the barcode?
> 
> Example this is the format:
> 
> ```
> 2D barcode,ABV:OB04;UPC:136141484313;EAN:12345678;PID:APID;UUID:aaa4e0ae-8aac-4780-b742-4c5ab1973a00;OBD:A0UXujSA1Q+j+y0ArbmJebz+yIzzszWQn8IplfByNRxxh9ryC5p1IeNgx0XH55+z/on1yAkeFqR8AKVoVnyO9s0o6MOmjbEJOZTzI0+cIy4VmOEWllPEKT0A+x1zxvCiSRNcSnDZE5izH9kjTRS63Kk=;
> ```
> 
> * The ABV will always is `OB04`, as I know because this is for the BLE device.
> * UPC: I tried to fake 12 digits but it didn't work
> * EAN: I fake this too
> * PID:APID, is this always `APID`?
> * OBD: I got by the DHA public key I generated
> 
> Thank you, @sksgits

If you are using WSS, and did not upload control log, the 2D barcode should include the PUK.
It seems that your example did not include the PUK.

**Comment by quynh-stel** [comment]
@sksgits 
Thank you for your reply.
I succeeded in the provisioning step when I submitted the correct test devices.

Now, I'm figuring how to get Wi-FI credential list from AWS Locker into ESP32.
I don't see any connection between ESP32 and my Echo Dot to detect the user identity.
Do you have any information about this, @sksgits ?
